config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

   def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path(@flats)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>All Our Flats (<%= @flats.count %>)</h1>. <%= link_to "Add a new flat", 'flats/new', class: "btn btn-primary" %>
    </div>
  </div>

<div class="cards-container">
  <div class="row">
     <% @flats.each do |flat| %>
     <div class="col-sm">
      <div class="flat-card">
         <div class="flat-card-content">
        <div class="flat-card-title">
          <h3><%= flat.name%></h3>
        </div>
        <p><%= flat.address %></p>
        <div class="flex-signs">
          <div class="flex">
            <i class="fas fa-dollar-sign"></i><span><%= flat.price_per_night %></span>
          </div>
          <div class="flex ml-3"><i class="fas fa-user-friends"></i> <span><%= flat.number_of_guests %></span>
          </div>
        </div>
         <div class="card-actions">
             <%= link_to "More Info", flat_path(flat) %>
          </div>
      </div>
      </div>
    </div>
     <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<p><%= @flat.address%></p>
<p><i class="fas fa-user-friends"></i><%= @flat.number_of_guests%></p>
<p><i class="fas fa-dollar-sign"></i><%= @flat.price_per_night%></p>
<p><%= @flat.description %></p>


<%= link_to "Back to all flats", "/flats", class: "btn btn-primary" %>
<%= link_to "Edit", edit_flat_path(@flat), class: "btn btn-primary" %>
<%= link_to "Delete",
     flat_path(@flat),
     method: :delete,
     data: { confirm: 'Are you sure you want to delete this flat?'},
     class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>